VIEWER_BACKGROUND_COLOR = "#1a1a1a"
BOUNDING_BOX_EDGE_COLOR = "#aaaaaa"
SPLIT_EDGE_COLOR = "black"
BOARD_COLOR = "white"
STRINGER_COLOR = "#deb887"
CUTLAP_COLOR = "#dceac2"

PIECE_RADIUS_MIN_MM = 40
PIECE_RADIUS_MAX_MM = 300
PIECE_RADIUS_DEFAULT_MM = 100

STRINGER_WIDTH_MIN_MM = 4
STRINGER_WIDTH_MAX_MM = 20
STRINGER_WIDTH_DEFAULT_MM = 4

CUTLAP_WIDTH_MIN_MM = 5
CUTLAP_WIDTH_MAX_MM = 50
CUTLAP_WIDTH_DEFAULT_MM = 20

WALL_WIDTH_MIN_MM = 0.1
WALL_WIDTH_MAX_MM = 10.0
WALL_WIDTH_DEFAULT_MM = 0.6

TOP_WIDTH_MIN_MM = 0.0
TOP_WIDTH_MAX_MM = 10.0
TOP_WIDTH_DEFAULT_MM = 0.0

BOTTOM_WIDTH_MIN_MM = 0.0
BOTTOM_WIDTH_MAX_MM = 10.0
BOTTOM_WIDTH_DEFAULT_MM = 0.0

HOLE_RADIUS_MIN_PCT = 0
HOLE_RADIUS_MAX_PCT = 80
HOLE_RADIUS_DEFAULT_PCT = 50
