VIEWER_BACKGROUND_COLOR = "#1a1a1a"
BOUNDING_BOX_EDGE_COLOR = "#aaaaaa"
SPLIT_EDGE_COLOR = "black"
BOARD_COLOR = "white"
STRINGER_COLOR = "#deb887"
CUTLAP_COLOR = "#dceac2"

PIECE_RADIUS_MIN_MM = 40
PIECE_RADIUS_MAX_MM = 300
PIECE_RADIUS_DEFAULT_MM = 100

STRINGER_WIDTH_MIN_MM = 4
STRINGER_WIDTH_MAX_MM = 20
STRINGER_WIDTH_DEFAULT_MM = 4

CUTLAP_WIDTH_MIN_MM = 5
CUTLAP_WIDTH_MAX_MM = 50
CUTLAP_WIDTH_DEFAULT_MM = 20
