VIEWER_BACKGROUND_COLOR = "#1a1a1a"
BOUNDING_BOX_EDGE_COLOR = "#aaaaaa"
SPLIT_EDGE_COLOR = "black"
BOARD_COLOR = "white"
STRINGER_COLOR = "#deb887"
CUTLAP_COLOR = "#dceac2"

PIECE_RADIUS_MIN_MM = 40
PIECE_RADIUS_MAX_MM = 300
PIECE_RADIUS_DEFAULT_MM = 100

STRINGER_WIDTH_MIN_MM = 4
STRINGER_WIDTH_MAX_MM = 20
STRINGER_WIDTH_DEFAULT_MM = 4

CUTLAP_WIDTH_MIN_MM = 5
CUTLAP_WIDTH_MAX_MM = 50
CUTLAP_WIDTH_DEFAULT_MM = 20

WALL_WIDTH_MIN_MM = 0.1
WALL_WIDTH_MAX_MM = 10.0
WALL_WIDTH_DEFAULT_MM = 0.6

TOP_WIDTH_MIN_MM = 0.0
TOP_WIDTH_MAX_MM = 10.0
TOP_WIDTH_DEFAULT_MM = 0.0

BOTTOM_WIDTH_MIN_MM = 0.0
BOTTOM_WIDTH_MAX_MM = 10.0
BOTTOM_WIDTH_DEFAULT_MM = 0.0

HOLE_RADIUS_MIN_PCT = 0
HOLE_RADIUS_MAX_PCT = 80
HOLE_RADIUS_DEFAULT_PCT = 50

LEASH_PLUG_DIAMETER_MIN_MM = 5
LEASH_PLUG_DIAMETER_MAX_MM = 60
LEASH_PLUG_DIAMETER_DEFAULT_MM = 26

LEASH_PLUG_DEPTH_MIN_MM = 1
LEASH_PLUG_DEPTH_MAX_MM = 100
LEASH_PLUG_DEPTH_DEFAULT_MM = 20

LEASH_PLUG_TAIL_DISTANCE_MIN_MM = 0
LEASH_PLUG_TAIL_DISTANCE_MAX_MM = 2000
LEASH_PLUG_TAIL_DISTANCE_DEFAULT_MM = 60

LEASH_PLUG_CENTER_MIN_MM = -40
LEASH_PLUG_CENTER_MAX_MM = 40
LEASH_PLUG_CENTER_DEFAULT_MM = 0

FIN_SINGLE_BOX_LONG_MIN_MM = 5
FIN_SINGLE_BOX_LONG_MAX_MM = 400
FIN_SINGLE_BOX_LONG_DEFAULT_MM = 267

FIN_SINGLE_BOX_WIDTH_MIN_MM = 10
FIN_SINGLE_BOX_WIDTH_MAX_MM = 30
FIN_SINGLE_BOX_WIDTH_DEFAULT_MM = 26

FIN_SINGLE_BOX_DEPTH_MIN_MM = 10
FIN_SINGLE_BOX_DEPTH_MAX_MM = 40
FIN_SINGLE_BOX_DEPTH_DEFAULT_MM = 26

FIN_SINGLE_TAIL_DISTANCE_MIN_MM = 0
FIN_SINGLE_TAIL_DISTANCE_MAX_MM = 1000
FIN_SINGLE_TAIL_DISTANCE_DEFAULT_MM = 250

FIN_TWIN_TAIL_DISTANCE_MIN_MM = 0
FIN_TWIN_TAIL_DISTANCE_MAX_MM = 1000
FIN_TWIN_TAIL_DISTANCE_DEFAULT_MM = 150

FIN_TWIN_CENTER_DISTANCE_MIN_MM = 0
FIN_TWIN_CENTER_DISTANCE_MAX_MM = 400
FIN_TWIN_CENTER_DISTANCE_DEFAULT_MM = 200

# Toe-in angle: how much each twin fin tilts toward the centreline (degrees).
FIN_TWIN_ANGLE_MIN_DEG = -30
FIN_TWIN_ANGLE_MAX_DEG = 30
FIN_TWIN_ANGLE_DEFAULT_DEG = 4

# Fixed prism size for the twin-fin markers (no dedicated inputs yet).
FIN_TWIN_BOX_LONG_MM = 120
FIN_TWIN_BOX_WIDTH_MM = 20
